POST http://localhost:3001/user/register
Content-Type: application/json

{
    "email": "superAdmin@gmail.com",
    "username": "Admin",
    "password": "Dancan2021@",
    "confirmPassword": "Dancan2021@"
}
###

POST  http://localhost:3001/user/login
Content-Type: application/json

{
    "email": "superAdmin@gmail.com",
    "password": "Dancan2021@"
}

###
PATCH   http://localhost:3001/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiQWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCQ1UmYvc3JrRW1DLi9YQ2JHT0VkekRPWEM1dVI1L1BDd3NhYXJxS3RTU0tKMGJLZFBidU1RaSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZUlkIjoxLCJpYXQiOjE2Mzg3OTQ4MTIsImV4cCI6MTYzODc5ODQxMn0.rGYqLXU5HjJz-m06L6ujvqjVqyg0iQEpNqHkBDNgCuc
Content-Type: application/json

{   "email": "dan2@gmail",
    "newUserName": "Email@2022#"
}

###
DELETE http://localhost:3001/user/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiQWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCQ1UmYvc3JrRW1DLi9YQ2JHT0VkekRPWEM1dVI1L1BDd3NhYXJxS3RTU0tKMGJLZFBidU1RaSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZUlkIjoxLCJpYXQiOjE2Mzg3OTQ4MTIsImV4cCI6MTYzODc5ODQxMn0.rGYqLXU5HjJz-m06L6ujvqjVqyg0iQEpNqHkBDNgCuc
Content-Type: application/json

{
    "email": "dandelete2@dan"
}



# admin
# username: admin
# email: admin@gmail.com
# password: Dancan2021@



# ---------------------PROJECTS--------------------------
###
GET http://localhost:3002/projects/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiQWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRBQW5IVkVVR3pxenRxRTU0V1RiSTlPUy53Q21BeGFsNTAwUnJhcjRUQ3BSYjI4YmIxUXd3MiIsImVtYWlsIjoic3VwZXJBZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE2MzkzMTU4ODksImV4cCI6MTYzOTMxOTQ4OX0.BVzKKF8cZ1i02On45q4oliCySuFtbApu4ZyErMDSHmo

###
GET http://localhost:3002/projects/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiQWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCQ0bWp1UFJCTWU5anAxSDV0ampLSVhlRXlOcjYuZ09TMW0vcVRRZGFGYXUyUUNOZDNUMHBwYSIsImVtYWlsIjoic3VwZXJBZG1pbkBnbWFpbC5jb20iLCJyb2xlSWQiOjEsImlhdCI6MTYzODg2OTA3NywiZXhwIjoxNjM4ODcyNjc3fQ.XOSJKxyzULR3uQjcyI7dMGOE7h2a3p_JQCfLIiTldyI

###
POST  http://localhost:3002/projects/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiQWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRBQW5IVkVVR3pxenRxRTU0V1RiSTlPUy53Q21BeGFsNTAwUnJhcjRUQ3BSYjI4YmIxUXd3MiIsImVtYWlsIjoic3VwZXJBZG1pbkBnbWFpbC5jb20iLCJyb2xlSWQiOjEsImlhdCI6MTYzOTM5NDE0MiwiZXhwIjoxNjM5Mzk3NzQyfQ.W2sMZ03tlX_TGTIqofUKQxMU0W1aNYqaL9cN09hKuU8
Content-Type: application/json

{
    "name": "Test",
    "description": "A simple Test"
}


###
PATCH  http://localhost:3002/projects/update/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiQWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCQ0bWp1UFJCTWU5anAxSDV0ampLSVhlRXlOcjYuZ09TMW0vcVRRZGFGYXUyUUNOZDNUMHBwYSIsImVtYWlsIjoic3VwZXJBZG1pbkBnbWFpbC5jb20iLCJyb2xlSWQiOjEsImlhdCI6MTYzODg4MTA1MiwiZXhwIjoxNjM4ODg0NjUyfQ.6T1Ia39zVVHVstyL6hzRIuy5ZS9y3_1figgv67Xhub0
Content-Type: application/json

{
    "name": "Perl Motors Eccommerce"
}

###
GET http://localhost:3002/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiQWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRBQW5IVkVVR3pxenRxRTU0V1RiSTlPUy53Q21BeGFsNTAwUnJhcjRUQ3BSYjI4YmIxUXd3MiIsImVtYWlsIjoic3VwZXJBZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE2MzkzMTU4ODksImV4cCI6MTYzOTMxOTQ4OX0.BVzKKF8cZ1i02On45q4oliCySuFtbApu4ZyErMDSHmo